exclude: ^tests/data/
repos:
- repo: https://gitlab.com/pycqa/flake8
  rev: 3.7.9
  hooks:
    - id: flake8
      args: [
        '--ignore=E203,E266,E501,W503,E221',
        '--max-line-length=100',
        '--max-complexity=18',
        '--select=B,C,E,F,W,T4,B9',
        '--exclude=build,__init__.py'
      ]
- repo: https://github.com/timothycrosley/isort
  rev: 5.2.1
  hooks:
    - id: isort
- repo: https://github.com/pre-commit/mirrors-yapf
  rev: v0.29.0
  hooks:
    - id: yapf
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.5.0
  hooks:
    - id: trailing-whitespace
    - id: check-yaml
      args: ['--unsafe']
    - id: end-of-file-fixer
    - id: requirements-txt-fixer
    - id: double-quote-string-fixer
    - id: fix-encoding-pragma
      args: ['--remove']
    - id: mixed-line-ending
      args: ['--fix=lf']
