from __future__ import absolute_import, division, print_function

import os

from transformers.data.utils import list_wiki_dir, parse_wiki_file


def parse_args():
    import argparse

    parser = argparse.ArgumentParser()
    parser.add_argument('--input', type=str, help='directory generated by Wikiextractor')
    parser.add_argument('--output', type=str, help='directory to saved files')

    args = parser.parse_args()
    return args


def main():
    args = parse_args()
    dirs, filenames_list = list_wiki_dir(args.input)
    for d, filenames in zip(dirs, filenames_list):
        output_dir = os.path.join(args.output, d)
        os.makedirs(output_dir, exist_ok=True)

        print('Processing {}'.format(d))
        for filename in filenames:
            input_file = os.path.join(args.input, d, filename)
            context = parse_wiki_file(input_file)

            output_file = os.path.join(args.output, d, filename)
            with open(output_file, 'w') as f:
                for c in context:
                    f.write(c + '\n')


if __name__ == '__main__':
    main()
