# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  linter:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install flake8==3.8.4 flake8-bugbear flake8-comprehensions
        python -m pip install isort==5.6.4 black==20.8b1
        if [ -f requirements.txt ]; then python -m pip install -r requirements.txt; fi
    - name: Lint
      run: |
        echo "Runing flake8"
        flake8 transformers/ tests/
        echo "Runing isort"
        isort --check-only transformeres/ tests/
        echo "Runing black"
        black transformers/ tests/

  test:

    runs-on: macos-latest
    strategy:
      matrix:
        python-version: [3.6]
        torch: [1.5, 1.6, 1.7]
        include:
          - torch: 1.5
            torchvision: 0.6
          - torch: 1.6
            torchvision: 0.7
          - torch: 1.7
            torchvision: 0.8

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: |
          ${{ env.pythonLocation }}/lib/python3.6/site-packages
          ~/.torch
        key: ${{ runner.os }}-torch${{ matrix.torch }}-${{ hashFiles('setup.py') }}-2020070
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest-xdist
        python -m pip install torch==${{matrix.torch}} torchvision==${{matrix.torchvision}} -f https://download.pytorch.org/whl/torch_stable.html
    - name: Build and install
      run: CC=clang CXX=clang++ python -m pip install -e .
    - name: Run unittests
      run: python -m pytest -n 4 -v tests/
